[toolchain]
channel = "nightly" # this OS requries experimental features only available in nightly
components = [
  "llvm-tools-preview", # bootimage crate depends on this
  "rust-src" # std lib source code. depended on by `.cargo/config.toml` "build-std" feature
]
